import type { Metadata } from "next";
import * as signalR from "@microsoft/signalr";
import { Inter } from "next/font/google";
import "./globals.css";
import { revalidatePath, revalidateTag } from "next/cache";

var connection = new signalR.HubConnectionBuilder()
  .withUrl("https://ordrd-dev.azurewebsites.net/orderQueue", {
    skipNegotiation: true,
    transport: signalR.HttpTransportType.WebSockets,
  })
  .build();

connection.start().then(() => {
  connection.invoke("SubscribeToRestaurant", "f29d3f0e-6fd8-466c-9e43-e94171404330").catch((err) => console.error(err));
});

connection.on("NewOrder", async (orders) => {
  revalidatePath(`/demo`, "layout");
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
